### ISSUE TITLE
Gitcoin Passport score problem

### ISSUE THREAD

**Issue by baibai131131** [passportxyz/passport-docs#16]
My Gitcoin Passport score is 22.69, but when I do the task, it is only 19.096. What's going on?
<img width="515" alt="1dd828e08cf67858c3315bc23c31957" src="https://github.com/passportxyz/passport-docs/assets/155156639/e24e1365-299d-4c5c-a8b4-4ddc2331ff51">
<img width="850" alt="c1b4465b01b37ffb6288af3864fc075" src="https://github.com/passportxyz/passport-docs/assets/155156639/45ff3f18-04c5-4b5a-b596-863bffb76193">

**Comment by lebraat** [comment]
This is not a support channel. Please use the support icon in the bottom-right corner of the app.
